version: 0.0
os: linux

files:
  - source: /target/javaproject-1.0-SNAPSHOT.jar
    destination: /usr/share/tomcat/webapps/
    overwrite: true

hooks:
  ApplicationStop:
    - location: scripts/stopserver.sh
      timeout: 300
      runas: root

  BeforeInstall:
    - location: scripts/install.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/startserver.sh
      timeout: 300
      runas: root
 
  ValidateService:
    - location: scripts/validate.sh
      timeout: 300
      runas: root
